name: 建议反馈
description: 展示你的想法
labels:
  - "建议"

body:
  - type: markdown
    attributes:
      value: |
        感谢你使用 WonderLab 建议反馈系统！
        
        如果此建议不符合模板，将会被无条件关闭。
  - type: textarea
    id: issue-description
    attributes:
      label: 建议描述
      description: 在此详细描述你的想法并阐述其原因
    validations:
      required: true

  - type: dropdown
    id: server-platform-type
    attributes:
      label: 操作系统版
      description: |
        选择你想在哪个平台上增加这项功能
      options:
        - Windows
        - Linux
        - Mac
        - 全平台
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 如有必要，你可以补充其他信息
